// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZbtzlBwD9g083LDgxNPW14aL0aA-ZcUo',
    appId: '1:891005719510:web:927926d23533ee0060ca77',
    messagingSenderId: '891005719510',
    projectId: 'museapp-bc740',
    authDomain: 'museapp-bc740.firebaseapp.com',
    storageBucket: 'museapp-bc740.appspot.com',
    measurementId: 'G-Y8KQPTXT07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTrmiQhdJnmN3D105xx9rXmoncOX9GFY4',
    appId: '1:891005719510:android:a36dd2a8b222342160ca77',
    messagingSenderId: '891005719510',
    projectId: 'museapp-bc740',
    storageBucket: 'museapp-bc740.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqmYEFJILZa2zHDCxJXdjwkUnCTbWgg00',
    appId: '1:891005719510:ios:622d440d26f61dfe60ca77',
    messagingSenderId: '891005719510',
    projectId: 'museapp-bc740',
    storageBucket: 'museapp-bc740.appspot.com',
    iosBundleId: 'com.example.muse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqmYEFJILZa2zHDCxJXdjwkUnCTbWgg00',
    appId: '1:891005719510:ios:622d440d26f61dfe60ca77',
    messagingSenderId: '891005719510',
    projectId: 'museapp-bc740',
    storageBucket: 'museapp-bc740.appspot.com',
    iosBundleId: 'com.example.muse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZbtzlBwD9g083LDgxNPW14aL0aA-ZcUo',
    appId: '1:891005719510:web:9f9f03780b2498db60ca77',
    messagingSenderId: '891005719510',
    projectId: 'museapp-bc740',
    authDomain: 'museapp-bc740.firebaseapp.com',
    storageBucket: 'museapp-bc740.appspot.com',
    measurementId: 'G-LJDEK14G5V',
  );
}
